### ISSUE TITLE
Improve link UX/usability for header links

### ISSUE THREAD

**Issue by xf-** [entropia/landing-page#56]
**Current state**
I'm unfamiliar with landing page (Home) and every Block/Col is the same style and only some titles are linked. Only a device with a cursor has any indicator at all.

**Possible solutions**
- Change Link color or add an underline/ border or something distinct for links (works also great on mobile)
  - `text-decoration: underline var(--color-brand-primary);` or
  - `border-bottom: 2px solid var(--color-brand-primary);`
- Add a stretched link, so a block/col/tile is clickable and triggers the hover effect easily.
  - Add `position: relative` to column
  - Add a class like `stretched-link` and an after element 
 ```css
.stretched-link::after {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 1;
  content: "";
}
```
_Based on [Bootstrap stretched-link](https://getbootstrap.com/docs/5.3/helpers/stretched-link/)_

![Screenshot](https://github.com/entropia/landing-page/assets/1295633/8ae8f77a-388d-443a-8844-0a05ec79c557)
